#!/bin/sh

export QT_QPA_PLATFORMTHEME=qt5ct
export GIO_USE_VOLUME_MONITOR=unix

export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus

create_cache_dir()
{
  local path="${HOME}/.cache"
  [ ! -L "${path}" ] && return
  local target=$(readlink "${path}")
  [ -d "${target}" ] && return
  mkdir -p "${target}"
}

if [ -f ~/.firstrun ]; then
  . ~/.firstrun
  rm -f ~/.firstrun
fi

create_cache_dir

# HiDPI: detect display DPI and apply UI scaling before the session
# (and thus every GTK/Qt process) starts. See nomadbsd-dpi(8)/handbook.
if [ -x /usr/libexec/nomadbsd-dpi ]; then
  /usr/libexec/nomadbsd-dpi apply
  [ -f ~/.config/nomadbsd/hidpi.env ] && . ~/.config/nomadbsd/hidpi.env
fi

. /usr/local/etc/xdg/xfce4/xinitrc

